# Generated by Django 4.2.27 on 2026-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('editor', '开发者'), ('viewer', '普通用户')], default='viewer', help_text='用户角色，如 admin、editor、viewer 等', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
